import type { MockPlannerState } from "@/app/_lib/planner-types";

export const mockPlannerState: MockPlannerState = {
  currentTime: "2026-03-25T10:20:00-08:00",
  dayPlan: {
    id: "day-plan-2026-03-25",
    date: "2026-03-25",
    planningWindow: {
      startTime: "2026-03-25T08:30:00-08:00",
      endTime: "2026-03-25T19:00:00-08:00",
    },
    rawInput: {
      createdAt: "2026-03-25T08:12:00-08:00",
      rawText: [
        "cardio review",
        "40 practice questions",
        "answer emails",
        "call insurance",
        "shower",
        "lunch",
        "tidy kitchen",
        "2:00 PM doctor appointment",
        "available 8:30 AM to 7:00 PM",
      ].join("\n"),
    },
    tasks: [
      {
        id: "task-shower",
        title: "Shower and reset",
        rawText: "shower",
        type: "self_care",
        estimatedMinutes: 20,
        priority: "medium",
        mustDoToday: true,
        breakEligible: false,
        splittable: false,
        deferrable: false,
        energyLevel: "low",
        source: "user",
      },
      {
        id: "task-cardio-review",
        title: "Cardio review",
        rawText: "cardio review",
        type: "deep_work",
        estimatedMinutes: 85,
        priority: "high",
        mustDoToday: true,
        breakEligible: false,
        splittable: true,
        deferrable: false,
        energyLevel: "high",
        source: "user",
      },
      {
        id: "task-practice-questions",
        title: "40 practice questions",
        rawText: "40 practice questions",
        type: "deep_work",
        estimatedMinutes: 110,
        priority: "critical",
        mustDoToday: true,
        breakEligible: false,
        splittable: true,
        deferrable: false,
        energyLevel: "high",
        source: "user",
      },
      {
        id: "task-emails",
        title: "Answer emails",
        rawText: "answer emails",
        type: "admin",
        estimatedMinutes: 20,
        priority: "low",
        mustDoToday: false,
        breakEligible: true,
        splittable: false,
        deferrable: true,
        energyLevel: "low",
        source: "user",
      },
      {
        id: "task-insurance",
        title: "Call insurance",
        rawText: "call insurance",
        type: "admin",
        estimatedMinutes: 20,
        priority: "medium",
        mustDoToday: true,
        breakEligible: false,
        splittable: false,
        deferrable: false,
        energyLevel: "medium",
        source: "user",
      },
      {
        id: "task-lunch",
        title: "Lunch",
        rawText: "lunch",
        type: "self_care",
        estimatedMinutes: 30,
        priority: "high",
        mustDoToday: true,
        breakEligible: false,
        splittable: false,
        deferrable: false,
        energyLevel: "low",
        source: "user",
      },
      {
        id: "task-kitchen",
        title: "Tidy kitchen",
        rawText: "tidy kitchen",
        type: "chore",
        estimatedMinutes: 20,
        priority: "low",
        mustDoToday: false,
        breakEligible: true,
        splittable: false,
        deferrable: true,
        energyLevel: "low",
        source: "user",
      },
    ],
    hardEvents: [
      {
        id: "event-doctor",
        title: "Doctor appointment",
        startTime: "2026-03-25T14:00:00-08:00",
        endTime: "2026-03-25T14:45:00-08:00",
        notes: "Fixed appointment anchor.",
        locked: true,
        source: "user",
      },
    ],
    blocks: [
      {
        id: "block-shower",
        taskId: "task-shower",
        title: "Shower and reset",
        blockType: "self_care",
        startTime: "2026-03-25T08:30:00-08:00",
        endTime: "2026-03-25T08:50:00-08:00",
        status: "done",
        locked: false,
        source: "mixed",
      },
      {
        id: "block-cardio-review-1",
        taskId: "task-cardio-review",
        title: "Cardio review",
        blockType: "focus",
        startTime: "2026-03-25T08:50:00-08:00",
        endTime: "2026-03-25T09:35:00-08:00",
        status: "done",
        locked: false,
        source: "mixed",
      },
      {
        id: "block-practice-questions-1",
        taskId: "task-practice-questions",
        title: "Practice questions · set 1",
        blockType: "focus",
        startTime: "2026-03-25T09:35:00-08:00",
        endTime: "2026-03-25T10:35:00-08:00",
        status: "active",
        locked: false,
        source: "mixed",
      },
      {
        id: "block-break-morning",
        title: "Tea and reset",
        blockType: "break",
        startTime: "2026-03-25T10:35:00-08:00",
        endTime: "2026-03-25T10:55:00-08:00",
        status: "upcoming",
        locked: false,
        source: "system",
        notes: "Explicit break block.",
      },
      {
        id: "block-emails",
        taskId: "task-emails",
        title: "Answer emails",
        blockType: "admin",
        startTime: "2026-03-25T10:55:00-08:00",
        endTime: "2026-03-25T11:15:00-08:00",
        status: "upcoming",
        locked: false,
        source: "mixed",
      },
      {
        id: "block-insurance",
        taskId: "task-insurance",
        title: "Call insurance",
        blockType: "admin",
        startTime: "2026-03-25T11:15:00-08:00",
        endTime: "2026-03-25T11:35:00-08:00",
        status: "upcoming",
        locked: false,
        source: "mixed",
      },
      {
        id: "block-practice-questions-2",
        taskId: "task-practice-questions",
        title: "Practice questions · set 2",
        blockType: "focus",
        startTime: "2026-03-25T11:35:00-08:00",
        endTime: "2026-03-25T12:20:00-08:00",
        status: "upcoming",
        locked: false,
        source: "mixed",
      },
      {
        id: "block-lunch",
        taskId: "task-lunch",
        title: "Lunch",
        blockType: "self_care",
        startTime: "2026-03-25T12:20:00-08:00",
        endTime: "2026-03-25T12:50:00-08:00",
        status: "upcoming",
        locked: false,
        source: "mixed",
      },
      {
        id: "block-kitchen",
        taskId: "task-kitchen",
        title: "Tidy kitchen",
        blockType: "chore",
        startTime: "2026-03-25T12:50:00-08:00",
        endTime: "2026-03-25T13:10:00-08:00",
        status: "upcoming",
        locked: false,
        source: "mixed",
        isBreakEligibleTaskPlacement: true,
      },
      {
        id: "block-cardio-review-2",
        taskId: "task-cardio-review",
        title: "Cardio review notes",
        blockType: "focus",
        startTime: "2026-03-25T13:10:00-08:00",
        endTime: "2026-03-25T13:50:00-08:00",
        status: "upcoming",
        locked: false,
        source: "mixed",
      },
      {
        id: "block-doctor",
        title: "Doctor appointment",
        blockType: "appointment",
        startTime: "2026-03-25T14:00:00-08:00",
        endTime: "2026-03-25T14:45:00-08:00",
        status: "upcoming",
        locked: true,
        source: "user",
        notes: "Fixed event anchor.",
      },
      {
        id: "block-transition",
        title: "Return and reset",
        blockType: "transition",
        startTime: "2026-03-25T14:45:00-08:00",
        endTime: "2026-03-25T15:00:00-08:00",
        status: "upcoming",
        locked: false,
        source: "system",
      },
      {
        id: "block-cardio-review-3",
        taskId: "task-cardio-review",
        title: "Cardio review recap",
        blockType: "focus",
        startTime: "2026-03-25T15:00:00-08:00",
        endTime: "2026-03-25T15:40:00-08:00",
        status: "upcoming",
        locked: false,
        source: "mixed",
      },
    ],
    breakMode: "productive",
    breakCadence: "focus_50",
    paceMode: "finish_sooner",
    completedTaskIds: [],
    activeBlockId: "block-practice-questions-1",
    createdAt: "2026-03-25T08:15:00-08:00",
    updatedAt: "2026-03-25T09:57:00-08:00",
  },
};
